export const ProductData = [
  {
    name: "Egusi Soup",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 800,
    id: "egusi_soup",
    quantity: 0,
  },
  {
    name: "Jollof Rice",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 400,
    id: "jollof_rice",
    quantity: 0,
  },
  {
    name: "White Rice",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "white_rice",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
  {
    name: "Stewed chicken",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pharetra mattis.",
    calories: 200,
    id: "stewed_chicken",
    quantity: 0,
  },
];
